import sagactLogo from '../assets/sagact-logo.png?inline'
import { formatBillingNumber } from './billing-number'

export type BillingPdfDetails = {
  projectName: string
  clientName: string
  location: string
  billingNumber: number
  amount: number
  progressPercent: number
  issuedAt: string
  dueAt: string | null
}

const amountFormat = new Intl.NumberFormat('en-PH', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
})

const money = (amount: number) => `PHP ${amountFormat.format(amount)}`

const dateFormat = new Intl.DateTimeFormat('en-PH', {
  month: 'long',
  day: 'numeric',
  year: 'numeric',
})

function formatDate(value: string) {
  const date = new Date(value.length === 10 ? `${value}T12:00:00` : value)
  return Number.isNaN(date.getTime()) ? value : dateFormat.format(date)
}

export async function createBillingPdf(details: BillingPdfDetails) {
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF({ format: 'a4', unit: 'mm' })
  const { registerRobotoFonts } = await import('./pdf-fonts')
  registerRobotoFonts(pdf)
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20

  pdf.setFillColor(237, 234, 233)
  pdf.rect(0, 0, pageWidth, 32, 'F')
  pdf.addImage(sagactLogo, 'PNG', margin - 8.24, -3.72, 40, 40)
  pdf.setTextColor(36, 43, 39)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(16)
  pdf.text('PROGRESS BILLING', pageWidth / 2, 54, { align: 'center' })

  pdf.setTextColor(32, 67, 54)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(10)
  pdf.text(`BILLING #${formatBillingNumber(details.billingNumber)}`, margin, 61)
  pdf.setFont('Roboto', 'normal')
  pdf.setTextColor(70, 78, 74)
  pdf.text(`Issued: ${formatDate(details.issuedAt)}`, margin, 69)
  pdf.text(`Due: ${details.dueAt ? formatDate(details.dueAt) : 'Upon receipt'}`, margin, 76)

  pdf.setDrawColor(218, 224, 220)
  pdf.line(margin, 86, pageWidth - margin, 86)

  pdf.setTextColor(107, 117, 110)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(9)
  pdf.text('BILL TO', margin, 99)
  pdf.text('PROJECT', pageWidth / 2, 99)
  pdf.setTextColor(36, 43, 39)
  pdf.setFont('Roboto', 'normal')
  pdf.setFontSize(12)
  pdf.text(pdf.splitTextToSize(details.clientName, 72), margin, 107)
  pdf.text(pdf.splitTextToSize(details.projectName, 72), pageWidth / 2, 107)
  pdf.setFontSize(10)
  pdf.setTextColor(90, 99, 93)
  pdf.text(pdf.splitTextToSize(details.location, 72), pageWidth / 2, 115)

  pdf.setFillColor(243, 246, 244)
  pdf.rect(margin, 135, pageWidth - margin * 2, 29, 'F')
  pdf.setTextColor(47, 57, 51)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(9)
  pdf.text('DESCRIPTION', margin + 6, 145)
  pdf.text('AMOUNT', pageWidth - margin - 6, 145, { align: 'right' })
  pdf.setFont('Roboto', 'normal')
  pdf.setFontSize(10)
  pdf.text(`Progress billing for work completed through ${details.progressPercent}%`, margin + 6, 155)
  pdf.text(money(details.amount), pageWidth - margin - 6, 155, { align: 'right' })

  pdf.setDrawColor(218, 224, 220)
  pdf.line(margin, 180, pageWidth - margin, 180)
  pdf.setTextColor(47, 57, 51)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(11)
  pdf.text('TOTAL DUE', pageWidth - margin, 193, { align: 'right' })
  pdf.setTextColor(32, 67, 54)
  pdf.setFontSize(16)
  pdf.text(money(details.amount), pageWidth - margin, 204, { align: 'right' })

  pdf.setFont('Roboto', 'normal')
  pdf.setFontSize(9)
  pdf.setTextColor(107, 117, 110)
  pdf.text(`Please include billing #${formatBillingNumber(details.billingNumber)} as your payment reference.`, margin, 223)
  pdf.line(margin, 276, pageWidth - margin, 276)
  pdf.setFontSize(8)
  pdf.text('Generated by SAGACT project workspace', margin, 283)

  return pdf
}

export async function openBillingPdf(details: BillingPdfDetails) {
  if (typeof window === 'undefined') return
  const preview = window.open('', '_blank')
  if (!preview) throw new Error('Allow pop-ups to view the billing PDF.')

  try {
    const pdf = await createBillingPdf(details)
    const blob = pdf.output('blob')
    const url = URL.createObjectURL(blob)
    preview.location.href = url
    preview.opener = null
    setTimeout(() => URL.revokeObjectURL(url), 60000)
  } catch (error) {
    preview.close()
    throw error
  }
}

export async function downloadBillingPdf(details: BillingPdfDetails) {
  const filePart = details.projectName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const pdf = await createBillingPdf(details)
  pdf.save(`SAGACT-Billing-${formatBillingNumber(details.billingNumber)}-${filePart || 'project'}.pdf`)
}