import sagactLogo from '../assets/sagact-logo.png?inline'

export type PaymentReceiptDetails = {
  projectName: string
  payerName: string
  receiptNumber: string
  amount: number
  receivedDate: string
  paymentType: 'down_payment' | 'progress' | 'retention_release' | 'other'
  paymentMode: 'cash' | 'bank_transfer' | 'check' | 'card' | 'other'
  reference: string
}

const amountFormat = new Intl.NumberFormat('en-PH', {
  minimumFractionDigits: 2,
  maximumFractionDigits: 2,
})

const money = (amount: number) => `PHP ${amountFormat.format(amount)}`
const dateFormat = new Intl.DateTimeFormat('en-PH', {
  month: 'long',
  day: 'numeric',
  year: 'numeric',
})

function formatDate(value: string) {
  const date = new Date(`${value}T12:00:00`)
  return Number.isNaN(date.getTime()) ? value : dateFormat.format(date)
}

const paymentTypeLabel: Record<PaymentReceiptDetails['paymentType'], string> = {
  down_payment: 'Down payment',
  progress: 'Progress payment',
  retention_release: 'Retention release',
  other: 'Other payment',
}

const paymentModeLabel: Record<PaymentReceiptDetails['paymentMode'], string> = {
  cash: 'Cash',
  bank_transfer: 'Bank transfer',
  check: 'Check',
  card: 'Card',
  other: 'Other',
}

export async function createPaymentReceiptPdf(details: PaymentReceiptDetails) {
  const { jsPDF } = await import('jspdf')
  const pdf = new jsPDF({ format: 'a4', unit: 'mm' })
  const { registerRobotoFonts } = await import('./pdf-fonts')
  registerRobotoFonts(pdf)
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20

  pdf.setFillColor(237, 234, 233)
  pdf.rect(0, 0, pageWidth, 32, 'F')
  pdf.addImage(sagactLogo, 'PNG', margin - 8.24, -3.72, 40, 40)
  pdf.setTextColor(36, 43, 39)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(15)
  pdf.text('ACKNOWLEDGEMENT RECEIPT', pageWidth / 2, 48, { align: 'center' })

  pdf.setTextColor(32, 67, 54)
  pdf.setFontSize(10)
  pdf.text(`RECEIPT #${details.receiptNumber}`, margin, 61)
  pdf.setFont('Roboto', 'normal')
  pdf.setTextColor(70, 78, 74)
  pdf.text(`Date received: ${formatDate(details.receivedDate)}`, margin, 70)

  pdf.setDrawColor(218, 224, 220)
  pdf.line(margin, 82, pageWidth - margin, 82)
  pdf.setTextColor(107, 117, 110)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(9)
  pdf.text('RECEIVED FROM', margin, 96)
  pdf.setTextColor(36, 43, 39)
  pdf.setFont('Roboto', 'normal')
  pdf.setFontSize(13)
  pdf.text(pdf.splitTextToSize(details.payerName, pageWidth - margin * 2), margin, 105)

  pdf.setFillColor(243, 246, 244)
  pdf.rect(margin, 121, pageWidth - margin * 2, 36, 'F')
  pdf.setTextColor(107, 117, 110)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(9)
  pdf.text('AMOUNT RECEIVED', margin + 7, 133)
  pdf.setTextColor(32, 67, 54)
  pdf.setFontSize(20)
  pdf.text(money(details.amount), margin + 7, 148)

  pdf.setTextColor(107, 117, 110)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(9)
  pdf.text('PAYMENT DETAILS', margin, 176)
  pdf.setDrawColor(218, 224, 220)
  pdf.line(margin, 181, pageWidth - margin, 181)

  pdf.setFont('Roboto', 'normal')
  pdf.setFontSize(10)
  pdf.setTextColor(70, 78, 74)
  pdf.text('Project', margin, 192)
  pdf.text(pdf.splitTextToSize(details.projectName, 110), margin + 45, 192)
  pdf.text('Payment type', margin, 204)
  pdf.text(paymentTypeLabel[details.paymentType], margin + 45, 204)
  pdf.text('Method', margin, 216)
  pdf.text(paymentModeLabel[details.paymentMode], margin + 45, 216)
  pdf.text('Reference', margin, 228)
  pdf.text(pdf.splitTextToSize(details.reference || 'Not provided', 110), margin + 45, 228)

  pdf.setTextColor(47, 57, 51)
  pdf.setFont('Roboto', 'bold')
  pdf.setFontSize(11)
  pdf.text('Received with thanks.', margin, 249)
  pdf.setDrawColor(150, 159, 153)
  pdf.line(margin, 268, margin + 65, 268)
  pdf.line(pageWidth - margin - 65, 268, pageWidth - margin, 268)
  pdf.setFont('Roboto', 'normal')
  pdf.setFontSize(8)
  pdf.setTextColor(107, 117, 110)
  pdf.text('Authorized signature', margin + 32.5, 274, { align: 'center' })
  pdf.text('Payer acknowledgment', pageWidth - margin - 32.5, 274, { align: 'center' })
  pdf.line(margin, 285, pageWidth - margin, 285)
  pdf.text('Generated by SAGACT project workspace', margin, 290)

  return pdf
}

export async function openPaymentReceiptPdf(details: PaymentReceiptDetails) {
  if (typeof window === 'undefined') return
  const pdf = await createPaymentReceiptPdf(details)
  const blob = pdf.output('blob')
  const url = URL.createObjectURL(blob)
  const preview = window.open(url, '_blank', 'noopener,noreferrer')
  if (preview) {
    preview.opener = null
  }
  setTimeout(() => URL.revokeObjectURL(url), 60000)
}

export async function downloadPaymentReceiptPdf(details: PaymentReceiptDetails) {
  const filePart = details.payerName.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
  const pdf = await createPaymentReceiptPdf(details)
  pdf.save(`SAGACT-Receipt-${details.receiptNumber}-${filePart || 'payment'}.pdf`)
}